# Generated by Django 4.2.6 on 2023-11-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_color', models.BooleanField(choices=[(True, 'Black'), (False, 'White')], verbose_name='Player color')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.BooleanField(choices=[(True, 'Black'), (False, 'White')], verbose_name='Player')),
                ('piece', models.CharField(max_length=2, verbose_name='Piece')),
                ('movement', models.CharField(max_length=2, verbose_name='Movement')),
                ('promoted', models.CharField(max_length=6, null=True, verbose_name='Promoted')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_api.game')),
            ],
        ),
    ]
