# Generated by Django 4.2.6 on 2023-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.BooleanField()),
                ('piece', models.CharField(max_length=2, verbose_name='Piece')),
                ('movement', models.CharField(max_length=2, verbose_name='Movement')),
                ('promoted', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
