# Generated by Django 4.2.6 on 2023-11-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.CharField(default='basic', max_length=20, verbose_name='Opponent'),
        ),
    ]
